// Copyright (c) 2024, 2026 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: guide-multipane
:projectid: jakarta-data
:page-duration: 15 minutes
:page-releasedate: 2024-01-01
:page-majorupdateddate: 2023-01-01
:page-description: Description - TODO
:page-tags: ['jakarta-ee']
:page-related-guides: []
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:source-highlighter: prettify
:page-seo-title: Jakarta Data - TODO
:page-seo-description: Jakarta Data - TODO
:guide-author: Open Liberty
= Data Persistence with Jakarta Data
[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

== What you'll learn

You will learn how to use https://jakarta.ee/specifications/data/1.0/jakarta-data-1.0[Jakarta Data] to store data as well as the simple, yet powerful options it provides for querying data. This will include writing queries that are created from the method name, as well as queries using annotations. Finally, you will learn about the https://jakarta.ee/specifications/data/1.0/jakarta-data-1.0#_jakarta_data_query_language[Jakarta Data Query Language (JDQL)].

The application demonstrates a number of different queries that are possible with Jakarta Data. Once you have completed the guide you can try writing your own queries with the provided sample data.

=== What is Jakarta Data?
Jakarta Data is a new data access specification being released with Jakarta EE 11. It provides a new API for simplified data access. Jakarta Data follows the Repository design pattern for data access, and allows for implementations which may support both SQL and NoSQL data stores. It also provides enhanced type safety with a Static Metamodel.

[role='command']
include::{common-includes}/gitclone.adoc[]

[role='command']
include::{common-includes}/twyb-intro-mvnw.adoc[]

This application allows you to run queries against a set of shipping packages which have a variety of dimensions and destinations.  Go to the http://localhost:9080 URL to see all the application data. You will see a column of queries, some of which will accept input. To start find the `findAll` query with no inputs. Selecting this will return all of the query data similar to the following:

[role="no_copy"]
----
ID  Length  Width   Height  Destination
1   10      20      10      Rochester
2   30      10      10      Austin
3   5       10      5       RTP
4   24      15      6       Rochester
5   15      7       2       Austin
6   8       5       3       Rochester
7   16      3       15      RTP
8   2       15      18      Rochester
----

You can then try some of the queries which use input to see how it changes which packages are returned. If you find the query named `findByLengthGreaterThan` and enter `25` in the box labeled length, you can then run the query by clicking the ➜ button. The result should look like the following, with only lengths greater than 25:

[role="no_copy"]
----
ID  Length  Width  Height  Destination
2   30      10	   10      Austin
16  38      16     25      Markham
----


[role='command']
include::{common-includes}/twyb-end-mvnw.adoc[]

== Creating an entity and repository

Navigate to the `start` directory to begin.
ifdef::cloud-hosted[]
```bash
cd /home/project/guide-jakarta-data/start
```
endif::[]

[role='command']
include::{common-includes}/devmode-mvnw-start.adoc[]

In Jakarta Data an entity defines the structure for persisting a piece of data. This structure is represented by a Java object and its associated fields. The entity you will work with in this guide is a record class called `Package.java`, which contains a few fields.

Package.java
[source, Java, linenums, role='code_column hide_tags=copyright,app-only']
----
include::finish/src/main/java/io/openliberty/guides/data/Package.java[]
----


Packages.java
[source, Java, linenums, role='code_column hide_tags=copyright,query-by-method,annotations,sorting,query-anno']
----
include::finish/src/main/java/io/openliberty/guides/data/Packages.java[]
----

A common pattern with repositories is to use the plural of the entity, so the repository you will be working with in this guide is called `Packages.java`. Repositories in Jakarta Data provide a simplified means for interacting with persistent data. They are annotated with the `@Repository` annotation. Jakarta Data provides several built-in repositories with common methods which can be extended with application-specific queries. The [hotspot=CrudRepository file=1]`CrudRepository` interface provides methods for Create, Read, Update, and Delete (CRUD) operations.

[hotspot=CrudRepository file=1]`CrudRepository` provides two options for persisting entities, `insert` and `save`. The first option `insert` will persist an entity only if the entity does not already exist. The `save` option will persist an entity even if it already exists, allowing it to be used for updating entities as well. [hotspot=CrudRepository file=1]`CrudRepository` provides a `delete` method for removing entities.

```java
Package p1 = new Package(1, 10f, 20f, 10f, "Rochester");
packages.insert(p1);
packages.save(p1);
packages.delete(p1);
```

== Query by Method Name

Query by Method Name allows you to write queries using a descriptive method name following a few intuitive rules on how the method name is structured.

Packages.java
[source, Java, linenums, role='code_column hide_tags=copyright,annotations,sorting,query-anno']
----
include::finish/src/main/java/io/openliberty/guides/data/Packages.java[]
----

[role="code_command hotspot file=0", subs="quotes"]
----
#Update the `Packages.java` class.#
`src/main/java/io/openliberty/guides/data/Packages.java`
----


This allows methods like [hotspot=findByLengthGreaterThan file=0]`findByLengthGreaterThan(float length)` or [hotspot=findByHeightBetween file=0]`findByHeightBetween(float minHeight, float maxHeight)` to automatically be turned into queries. Method names must start with an action like `find`, `delete`, or `count` and can include operators (such as `And`, `Or`, and `Not`) and conditions (such as `GreaterThan`, `LessThan`, and `Between`).

For more information on all of the options available with Query by Method Name, see the https://jakarta.ee/specifications/data/1.0/jakarta-data-addendum-1.0.pdf[Query by Method Name Extension] of the Jakarta Data specification.

== Querying with method annotations

Queries can also be written using method annotations. This allows for additional flexibility in the queries as well as the method names.

Packages.java
[source, Java, linenums, role='code_column hide_tags=copyright,sorting,query-anno']
----
include::finish/src/main/java/io/openliberty/guides/data/Packages.java[]
----

[role="code_command hotspot file=0", subs="quotes"]
----
#Update the `Packages.java` class.#
`src/main/java/io/openliberty/guides/data/Packages.java`
----

=== The `@Find` and `@By` annotations
The [hotspot=Find file=0]`@Find` annotation indicates that a method is a query which may return entities. Used in isolation it will
return all entities, but by using the [hotspot=By file=0]`@By` annotation, it can be limited to entities which match the value provided at runtime. The [hotspot=getPackagesArrivingIn file=0]`getPackagesArrivingIn` method demonstrates using the [hotspot=Find file=0]`@Find` and [hotspot=By file=0]`@By`
annotations to return all packages that are destined for a specific location.


=== Renaming provided methods
If a method name provided by a built in Jakarta Data repository class doesn't align with your repository you can use annotations to provide your own method. For example, using the [hotspot=Insert file=0]`@Insert` annotation you can create a method named [hotspot=add file=0]`add` instead of the `insert` method inherited from [hotspot=CrudRepository file=0]`CrudRepository`.

This method is functionally equivalent to the `insert` method provided by [hotspot=CrudRepository file=0]`CrudRepository`.


=== The `@OrderBy` annotation
To provide ordering annotatively, you can use the [hotspot=OrderBy file=0]`@OrderBy` annotation. The default ordering direction is ascending. The [hotspot=sortedByHeightAscending file=0]`sortedByHeightAscending` method demonstrates how to obtain all of the packages in the repository sorted by the height parameter.

`@OrderBy` can also return in descending order by specifying `descending = true` in the annotation:

```java
@OrderBy(value = "height", descending = true)
```

== Sorting, limiting, and paging results
Jakarta Data provides the `Sort` and `Limit` classes to create queries which can be modified at runtime. It also includes a mechanism for pagination to better handle large sets of results.

Packages.java
[source, Java, linenums, role='code_column hide_tags=copyright,query-anno']
----
include::finish/src/main/java/io/openliberty/guides/data/Packages.java[]
----

[role="code_command hotspot file=0", subs="quotes"]
----
#Update the `Packages.java` class.#
`src/main/java/io/openliberty/guides/data/Packages.java`
----

=== Sort
In addition to the `@OrderBy` annotation it is possible to provide sorting at runtime. This is accomplished by adding a [hotspot=Sort file=0]`Sort` parameter to your query method like in the [hotspot=Sort file=0]`sorted` method.

A [hotspot=Sort file=0]`Sort` can be created and provided at runtime using the [hotspot=Sort file=0]`Sort` class's static methods:
```java
Sort sort = Sort.desc("height");
```

=== Limit
Jakarta Data queries can restrict the number of entities returned at runtime by providing a [hotspot=Limit file=0]`Limit` object to the query as shown in the [hotspot=Limit file=0]`shortestWithLimit` method.

This method will return the shortest packages in order from shortest to longest, but limited to only the specified number of results.

Limits can be created and supplied using the [hotspot=Limit file=0]`Limit` class's static methods:
```java
Limit limitTen = Limit.of(10);
```

Limits can also be used to access a range of entities, such as starting at the 10th entity and ending at the 20th:
```java
Limit range = Limit.range(10,20);
```


=== Paging
When querying large amounts of data, paging is possible by adding a [hotspot=PageRequest file=0]`PageRequest` parameter to your query method like in the [hotspot=PageRequest file=0]`all` method. This method will return all of the packages, but with the results paginated based on the provided [hotspot=PageRequest file=0]`PageRequest`.

A [hotspot=PageRequest file=0]`PageRequest` can be constructed with the [hotspot=PageRequest file=0]`PageRequest` class's static methods. To request the first [hotspot=Page file=0]`Page` with a page size of 20 results:

```java
Page<Package> page = packages.all(PageRequest.ofSize(20));
List<Package> results = page.content();
```

Navigating pages can be done from the `Page` object:

```java
Page<Package> anotherPage = packages.all(page.nextPageRequest());
```

== The Query Annotation
The `@Query` annotation allows users to write queries using the Jakarta Data Query Language (JDQL). Complex queries can be written concisely using JDQL. JDQL is a strict subset of the Jakarta Persistence Query Language (JPQL).

Packages.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/data/Packages.java[]
----

[role="code_command hotspot file=0", subs="quotes"]
----
#Update the `Packages.java` class.#
`src/main/java/io/openliberty/guides/data/Packages.java`
----

For an example of a complex query simplified using JDQL, take a look at [hotspot=withAnyDimensionLargerThan file=0]`withAnyDimensionLargerThan`.

This query checks for packages where the length, height, or width are larger than a threshold, which is provided as a parameter in the function. The threshold parameter is referenced in the query using `:threshold`. Achieving the same query with Query by Method Name would result in a very long method name and additional parameters.


JDQL supports both named and positional parameters, as well as a number of operators. This is shown in the [hotspot=withTotalDimensionOver file=0]`withTotalDimensionOver` query, which sums the length, width, and height of each package to check if the total exceeds a provided threshold. Unlike the named parameter syntax (`:threshold`) used in the previous example, this query uses positional parameter syntax with `?1` to reference the first method parameter.

See the https://jakarta.ee/specifications/data/1.0/jakarta-data-1.0#_jakarta_data_query_language[Jakarta Data specification] for a more comprehensive overview of the Jakarta Data Query Language.

== Where to next?
Experiment by creating your own queries. Use the existing ones in the `Packages` class as a starting point and then test them out in the sample application. For example, you could add a query to find packages arriving at a specific destination, which is ordered by width:

```java
    @Find
    @OrderBy("width")
    List<Package> byWidthArrivingIn(@By("destination") String destination);
```

//Eventually link to an Advanced Guide as well.