// Copyright (c) 2024 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: guide-multipane
:projectid: jakarta-data
:page-duration: 500 minutes
:page-releasedate: 2024-01-01
:page-majorupdateddate: 2023-01-01
:page-description: Description - TODO
:page-tags: ['jakarta-ee']
:page-related-guides: []
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:source-highlighter: prettify
:page-seo-title: Jakarta Data - TODO
:page-seo-description: Jakarta Data - TODO
:guide-author: Open Liberty
= Data Persistence with Jakarta Data
[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

== What you'll learn

You will learn how to use Jakarta Data to store data as well as the simple, yet powerful options it provides for querying data. This will include writing queries that are created from the method name, as well as queries using annotations. Finally, you will learn about the Jakarta Data Query Language (JDQL).

The application demonstrates a number of different queries that are possible with Jakarta Data. Once you have completed the guide you can try writing your own queries with provided sample data.

=== What is Jakarta Data?
Jakarta Data is a new data access specification being released with Jakarta EE 11. It provides a new API for simplified data access. Jakarta Data follows the Repository design pattern for data access, and allows for implementations which may support both SQL and NoSQL data stores. It also provides enhanced type safety with a Static Metamodel.

[role='command']
include::{common-includes}/gitclone.adoc[]

[role='command']
include::{common-includes}/twyb-intro.adoc[]
//TODO explain the application

== Creating an Entity and Repository

In Jakarta Data an entity defines the structure for persisting a piece of data. This structure is represented by a Java object and it's associated fields. Start by creating a simple record class.

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `Package` class.#
`src/main/java/io/openliberty/guides/data/Package.java`
----

Package.java
[source, Java, linenums, role='code_column hide_tags=copyright,app-only']
----
include::finish/src/main/java/io/openliberty/guides/data/Package.java[]
----

This is a simple entity, with a few fields. 

//TODO Packages or PackageRepository?
[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `Packages.java` class.#
`src/main/java/io/openliberty/guides/data/Packages.java`
----

Packages.java
[source, Java, linenums, role='code_column hide_tags=copyright,query-by-method,annotations,sorting,query-anno']
----
include::finish/src/main/java/io/openliberty/guides/data/Packages.java[]
----

Repositories in Jakarta Data provide a simplified means for interacting with persistent data. Jakarta Data provides several built in Repositories with common methods which can be extended. The [hotspot=CrudRepository file=1]`CrudRepository` interface provides methods for Create, Read, Update, and Delete (CRUD) operations.

== Query by Method Name

----
#Update the `Packages.java` class.#
`src/main/java/io/openliberty/guides/data/Packages.java`
----
Packages.java
[source, Java, linenums, role='code_column hide_tags=copyright,annotations,sorting,query-anno']
----
include::finish/src/main/java/io/openliberty/guides/data/Packages.java[]
----

== Using Annotations

----
#Update the `Packages.java` class.#
`src/main/java/io/openliberty/guides/data/Packages.java`
----
Packages.java
[source, Java, linenums, role='code_column hide_tags=copyright,sorting,query-anno']
----
include::finish/src/main/java/io/openliberty/guides/data/Packages.java[]
----

=== The `@Find` and `@By` Annotations
The `@Find` annotation indicates that a method is a query which may return entities. Used in isolation it will
return all entities, but by using the `@By` annotation, it can be limited to entities which match the value provided at runtime.

```java
@Find
List<Package> getPackagesArrivingIn(@By("destination") String destination);
```

//TODO should we mention --parameters at this point?

// TODO provided vs built-in?
=== Renaming provided methods
If a method name provided by a built in Jakarta Data repository class doesn't align with your repository you can use annotations to provide your own method. For example, using the `@Insert` annotation you can use `add` instead of the `insert` method inherited from `CrudRepository` like this.

```java
@Insert
void add(Package p);
```

This method is functionally equivalent to the `insert` method provided by `CrudRepository`.


=== The `@OrderBy` Annotation
To provide ordering annotatively, you can use the `@OrderBy` annotation. The default ordering direction is ascending. To obtain all of the entities in a repository sorted by the height parameter, you could use the following.

```java
@Find
@OrderBy("height")
List<Package> sortedByHeightAscending();
```

`@OrderBy` can also return in descending order by specifying `descending = true` in the annotation.

```java
@OrderBy(value = "height", descending = true)
```
//TODO rename? Runtime Modifications...?
== Sort, Limit, and Paging 
Jakarta Data provides the `Sort` and the `@Limit` annotation to create queries which can be modified at runtime. It also includes a mechanism for paging to better handle large sets of results.

----
#Update the `Packages.java` class.#
`src/main/java/io/openliberty/guides/data/Packages.java`
----
Packages.java
[source, Java, linenums, role='code_column hide_tags=copyright,query-anno']
----
include::finish/src/main/java/io/openliberty/guides/data/Packages.java[]
----

=== Sort
In addition to the `@OrderBy` annotation it is possible to provide sorting at runtime. This is accomplished by adding a `Sort` as a parameter to your query method.

```java
@Find
List<Package> sorted(Sort<?> sortBy);
```

A `Sort` can be created and provided at runtime using the Sort class's static methods:
```java
Sort sort = Sort.desc("height");
```

=== Limit
Jakarta Data queries can restrict the number of results returned at runtime by providing a `Limit` object to the query.

```java
List<Package> longestWithLimit(Limit limit);
```

Limits can be created and supplied using the Limit class's static methods:
```java
Limit limitTen = Limit.of(10);
```

Limits can also be used to access a range of results, such as starting at result 10 and ending at result 20:
```java
Limit range = Limit.range(10,20);
```


=== Paging
When querying large amounts of data, paging is possible by providing a `PageRequest` in a query.

```java
@Find
Page<Package> allWithPaging(PageRequest pageRequest);
```

A `PageRequest` can be constructed with the `PageRequest` class's static methods. To request the first page with a page size of 20 results:

```java
Page<Package> page = packages.allWithPaging(PageRequest.ofSize(20));
List<Package> results = page.content();
```

Navigating pages can be done from the `Page` object:

```java
Page<Package> anotherPage = packages.allWithPaging(page.nextPageRequest()); //TODO should we include .withoutTotal() ?
```

== The Query Annotation
The `@Query` annotation allows users to write queries using the Jakarta Data Query Language (JDQL). Complex queries can be written concisely using JDQL.

----
#Update the `Packages.java` class.#
`src/main/java/io/openliberty/guides/data/Packages.java`
----
Packages.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/data/Packages.java[]
----

```java
@Query("WHERE length > :threshold OR height > :threshold OR width > :threshold")
List<Package> withDimensionLargerThan(float threshold);
```

Achieving the same query with Query by Method Name would result in a very long method name and additional parameters. JDQL is a strict subset of the Jakarta Persistence Query Language (JPQL), supporting named and ordinal parameters, as well as a number of operators.

```java
@Query("WHERE length + width + height > ?1")
List<Package> withTotalDimensionOver(float threshold);
```

See the Jakarta Data specification for a more comprehensive overview of the Jakarta Data Query Language.

== Where to next?
Try out the sample application by creating your own queries. Add queries to the 

//Eventually link to an Advanced Guide as well.